### ISSUE TITLE
Auto Order (customer selectable)

### ISSUE THREAD

**Issue by macbookandrew** [UltraCart/rest_api#10]
Do you have any examples of the code I need in the checkout process for allowing customer-selectable auto orders?

Thanks

**Comment by perrytew** [comment]
Andrew,
From our conversations, you've probably moved on another project a long time ago, but I'm closing out this issue.  We've implemented customer selectable support in the rest checkout.  

Cheers,
Perry

**Comment by macbookandrew** [comment]
@perrytew Thanks for the update; I’m sure it will be helpful to others or myself on future projects
