### ISSUE TITLE
Sorting items

### ISSUE THREAD

**Issue by macbookandrew** [UltraCart/rest_api#11]
Do you have any way to sort the items called via /rest/site/items on the server before sending them (part of the request I make), or would I need to do it once the proxy script has returned the data from the server?

**Comment by ucjonathan** [comment]
Sorting is left up to the client side.  Good example of sorting in
JavaScript on this StackOverflow article:



http://stackoverflow.com/questions/5503900/how-to-sort-an-array-of-objects-with-jquery-or-javascript





*From:* Andrew Minion [mailto:notifications@github.com]
*Sent:* Friday, January 02, 2015 5:36 PM
*To:* UltraCart/rest_api
*Subject:* [rest_api] Sorting items (#11)



Do you have any way to sort the items called via /rest/site/items on the
server before sending them (part of the request I make), or would I need to
do it once the proxy script has returned the data from the server?

—
Reply to this email directly or view it on GitHub
<https://github.com/UltraCart/rest_api/issues/11>.[image: Image removed by
sender.]
