### ISSUE TITLE
how to captured authorize order ?

### ISSUE THREAD

**Issue by niravmeh** [UltraCart/rest_api#12]
Hi,

In our checkout process is set in two steps.
1) Authorization and 2) capture.

I want to capture the authorised order through rest api and process the payment.

which method i should use?   I have  1) merchant id and 2) customer id and 3) order id.

so I need to know the method name which will process the credit card and take the payments from authorised order.

Regards,
Nirav

**Comment by perrytew** [comment]
The behavior of payment gateways (auth-then-capture, etc) is controlled solely on the back end secure.ultracart.com configuration.  There is no means through the REST API of controlling payment gateway behavior.

The REST API can be used to take an order, and once the checkout or finalizeOrder method has been called, the gateway will be notified.  That is the limit of its ability.
