### ISSUE TITLE
Error when trying to get the redirect URL to finalize order

### ISSUE THREAD

**Issue by psupena** [UltraCart/rest_api#13]
Hello! 
I am pretty new to the Ultracart REST API, and my project is about integrating it into a custom checkout page.

I have read the documentation and tested out the samples from the demo, as well as the files here.
My final hurdle is getting the redirect URL. 
When I send my final checkout request, what I get is an error with the Credit Card number, 
See here: http://screencast.com/t/OonTjaXGf1i .

NOW, I searched and tested if somewhere along the way, before I run the final checkout request, I display the object and I get the masked number http://screencast.com/t/DJJp1aoom , which should be correct right? . I then checked and displayed the Credit Card Number Before and After I store it, and the masked and unmasked versions basically seem ok: http://screencast.com/t/vhXIqjIzyfZ .

Is there anyway to check if the CC was stored correctly at the UCCheckoutAPICardStore? 

I am using actually what is here: http://docs.ultracart.com/display/ucdoc/Collecting+Credit+Card+Numbers+with+Rest+API ,

Which is basically what is also in code block 6 here: https://github.com/UltraCart/rest_api/blob/master/call_examples/rest_examples.html . 

so I was thinking it is in the CC storage. 

Any help with be greatly appreciated.

**Comment by perrytew** [comment]
Hello.
The most common cause of this error is a cart id mismatch.   Somehow the cart id passed into token.ultracart.com doesn't match the cart's id when submitted.  This can happen in a number of different ways. 

Please log out the cart id that is passed to the store card function.  Compare that to the cart id used during the checkout/finalization routine.  Make sure they match.

If you could provide me with a public site, I could walk through the process and see where the issue lay.

Thanks,
Perry

**Comment by psupena** [comment]
Thank you very much for the reply!

This is our test page. I setup a test CC number in Ultracart already.
No need to enter any info, you just need to click on the button to go through the process. 
For now we are just testing actually if we can make a test order.

http://ztrackingsystem.com/financing-standalone/index.php 

Thank you very much for the help!

**Comment by psupena** [comment]
Hello! Just to update, I did compare the Cart ID's before and after the store card function was called.

I actually displayed it already in the page for testing: http://ztrackingsystem.com/financing-standalone/ 

It seems that I do send the same cartId's . That is why I want to trace if maybe it is in the side of token.ultracart.com? Do we need specific settings in the dashboard of ultracart to work? Besides setting  up the test CC numbers, and the test product.

Thank you very much!

**Comment by perrytew** [comment]
I'm investigating.

**Comment by perrytew** [comment]
Okay.  We've found an issue and fixed it.  To summarize, a few weeks ago we put in some caching to help prevent thousands of empty carts from being created when some of our API calls were made.   It worked fine when the cart was created, updated, card stored, and then finalized.  But your progression was such that the card was stored against an empty cart and then cleansed.  (our bad).   We've adjusted the code to prevent this and we've tested it out.  Looks good.

Please try your process again.    Sorry for the delay.  We're continuously working to improve the API in response to the heavy uptake its seeing.  

Thanks,
Perry

**Comment by psupena** [comment]
Thank you Perry! That solved the issue quite well.
I guess you guys can close this already.
