### ISSUE TITLE
How to get cart ID when using 2 domains?

### ISSUE THREAD

**Issue by leekudos** [UltraCart/rest_api#15]
Hi,

Im using my own domain for the main site and secure.ultracart.com for the checkout.

How can I use the REST API to pull a summary of the cart contents?

I obviously need the cartId but due to the different root domains in use I cant access the checkout ID.

I have created a new cart and set up the cartId, but obviously when I browse through to the cart page (on secure.ultracart.com), it generates a new cartID due to the domain being different.

Is there any way around this?

Thanks
Lee

**Comment by perrytew** [comment]
Hello.
The rest_proxy.php script was designed to reside on your server and provide a work around for the cross domain restrictions.

http://docs.ultracart.com/display/ucdoc/UltraCart+REST+Checkout+API#UltraCartRESTCheckoutAPI-Introduction(Thingsyou'llwishyoureadfirst)
