### ISSUE TITLE
Create gift certificate using api

### ISSUE THREAD

**Issue by prakash123** [UltraCart/rest_api#16]
I have developed an shopping cart system using Ultracart api and should have the user section to create gift certificate for certain amount. and I have to do this by using api. Please suggest me whether it is possible using api or not. Is there any other alternative to accomplish this task. Please help.

**Comment by perrytew** [comment]
Hello.
I'm not sure exactly what you're trying to accomplish, so I'll list out answers to a few possibilities.

1. There is no way to *create* a gift certificate.  This must be done manually via the secure.ultracart.com web site.  The merchant must login and create it there.

2. To *apply* a gift certificate to a shopping cart, you would set the cart.giftCertificate field to the certificate code and then update the cart.

See http://docs.ultracart.com/display/ucdoc/UltraCart+REST+Checkout+API#UltraCartRESTCheckoutAPI-Cart and look at the giftCertificate fields.  After you update the cart, the other giftCertificate fields will be populated with the various amounts.

**Comment by prakash123** [comment]
My requirement is similar functionality as https://www.thegr.com/index.cfm?event=egiftcard
