### ISSUE TITLE
hosted fields ie8 compatibility

### ISSUE THREAD

**Issue by JeffreyHWright** [UltraCart/rest_api#19]
![tab broken](https://cloud.githubusercontent.com/assets/5550887/8323539/28263b9a-1a03-11e5-9856-7c62c7d091e6.png)
![iframe broken](https://cloud.githubusercontent.com/assets/5550887/8323763/feb41676-1a05-11e5-9c97-1416b392f049.png)

It's possible that somehow I missed something, but it appears that the hosted fields code does not support ie8 too well, which I honestly wish I never had to discover.  I can work around the iframe border by changing the hosted fields js file to use iframeBorder="0" on line 220, but this leaves me in a position of hosting my own version of the file which is not recommended.

**Comment by perrytew** [comment]
Hey Jeffrey, thanks for the post.  We've worked through a lot of browser quirks so far.  I'm not sure how much they've done with IE8 to date, but we have a team that will look at this.  (Thankfully that team does not include me...)

Is there any way you could give us some code?   Do you have this page on a publicly accessible site that we can test with?

Thanks!
Perry

**Comment by superck007** [comment]
Hello  Perry,
I try implementations hosted credit card fields in javascript / REST API checkout page. However now I can't pass a valid credit card number through in my javascript code. How can I use these hosted fields in conjunction with the javascript REST API?

![code1](https://cloud.githubusercontent.com/assets/6998146/9719659/b30c0792-55b0-11e5-99f5-4efca4187ece.jpg)

![code2](https://cloud.githubusercontent.com/assets/6998146/9719662/ba7e6452-55b0-11e5-8540-6ce64245c8ea.jpg)

![code3](https://cloud.githubusercontent.com/assets/6998146/9719685/f964f438-55b0-11e5-9d9c-f811a4b49e4a.jpg)

**Comment by perrytew** [comment]
First, the IE8 implementation should be supported well now.  I say that to address the original issue. 

Second, superck, whenever I see a successful result from a hosted fields call and an invalid credit card, I check the following:
1. Please be sure the card you're testing with is set up as a test cart in your merchant's payment section.
2. Please be sure the cart id that is passed to the hosted fields setup call is the same as the one passed in the checkout request.  If those two don't match, the server can't assign the credit card to the shopping cart. 

If you have a public url of this implementation, I could look and see what's wrong.

Thanks,
Perry

**Comment by superck007** [comment]
Perry
it's working now..the problem is cardID. thanks :)
