### ISSUE TITLE
Getting 400 Bad Request But Dont Know Why...

### ISSUE THREAD

**Issue by leeovery** [UltraCart/rest_api#21]
Hi,

I'm running the this test bed locally and am getting different results when I test it on different setups.

I'm wondering if you know which of the following would be causing my problem...

* I run the API on my local mac installed apache installation and it works fine. I get a 200 status code and the results I expect.
* I run the API on my local mac but on a Nginx installation provided by Laravel Homestead and with exactly the same code I get a 400 Bad Request error, with the following text returned: "Invalid RequestAn internal error has occurred.  UltraCart Support has been notified."

The local apache server is being served up on IP:port 127.0.0.1:80. Whereas the Nginx server is being served up on the IP 192.168.10.10:80.

To save me testing a load of stuff I wanted to reach out to see if you knew what could be causing my issues. The error happens when I try to add items to the cart. The weird thing is I can generate an empty cart in both of the above scenarios without getting an error.

I'm using the most updated version of the rest_proxy script.

Any direction here would be massively appreciated.

Thanks
Lee

**Comment by leekudos** [comment]
Ive done a bit of digging into this and have fixed it. However I dont know exactly why this worked.

Whilst looking for the reason I narrowed it down to a header in the cURL response. Specifcially, when I commented out these lines...

$header[] = "Content-Type: " . $content_type;
$header[] = "Content-Length: " . strlen($post_data);

...the request worked.

What Ive actually done now is hard coded the following:

curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Content-Type: application/json',
    'Cache-Control: no-cache',
    'X-UC-Forwarded-For: ' . $_SERVER['REMOTE_ADDR'],
    'X-UC-Merchant-Id: myid',
    'X-UC-Proxy-Version: ' . $rest_proxy_version,
    'Expect: ',
));

This gets around the issue. This helped too: https://github.com/UltraCart/rest_api/issues/7

Thanks
Lee
