### ISSUE TITLE
Adding an item to the cart

### ISSUE THREAD

**Issue by taylortizzay** [UltraCart/rest_api#22]
Sorry, I'm super new to this API. I downloaded the cart example and uploaded it here http://languageofdesire.com/uc/cart_example/template.html I only have one product that has a flat price and no variation in options. How do I set up the one item in this cart? I am not really sure how to pass the API data that will render on this page. I have read all of the basic instructions here http://docs.ultracart.com/display/ucdoc/UltraCart+REST+Checkout+API but it seems as if there are many ways to accomplish this, but I really wanted to use this cart that is already set up. Any help would be greatly appreciated. 

Thank you

**Comment by perrytew** [comment]
The cart object has an array named items.  Add an item object to that
array and pass the cart to the /rest/cart (PUT) rest call. It will be
added to the cart.

The object API is out on docs.ultracart.com.  search for "checkout rest".

var items = [];
items.push( {itemId:'myitemid',quantity:1});
cart.items = items;
