### ISSUE TITLE
Email Validation: Space after email

### ISSUE THREAD

**Issue by rflournoy** [UltraCart/rest_api#23]
Hello, we ran into a situation where a customer left a space at the end of their email and was unable to checkout. Hunter mentioned that he recalled that a "trim" functionality was added.

Is that the case? If not, do you have other idea?

Thank you

**Comment by perrytew** [comment]
Hmmm.... what checkout?  Is this a custom checkout?  
If so, please give me the url so I can attempt to replicate the issue. 
Any clue what the error message was when they tried to checkout?

Thanks.

**Comment by perrytew** [comment]
Just noticed it was you, Robert.  I've got your web site url still loaded in my browser.  So, all they did was add a trailing space and the checkout choked?

**Comment by perrytew** [comment]
I tried to enter a trailing space, and your javascript validation wouldn't let me proceed with the checkout.  Any clue how they managed to get a trailing space in there and get the checkout fired off?

**Comment by rflournoy** [comment]
You can see in the developer log... i can put in an email with an extra space, use my address and a test card. In the logs I see ""errors": ["Please specify your email."]"

**Comment by perrytew** [comment]
I still can't get past the validation ... but, here's a fix for anyone who can with a trailing space.
In the file cart_1.0.js, lines 394-397:

```
      if(currentId == 'field-email'){
        if(!isValidEmailAddress(currentValue)) currentValue = '';
        cart.email = currentValue;
      }
```

Add the line below to make it this:
```
      if(currentId == 'field-email'){
        currentValue = jQuery.trim(currentValue);
        if(!isValidEmailAddress(currentValue)) currentValue = '';
        cart.email = currentValue;
      }
```

That will eliminate any trailing spaces.

**Comment by perrytew** [comment]
Robert,
Closing ticket.  Reopen it if you are still having issues.  

Thanks.
