### ISSUE TITLE
/rest/cart/finalizeOrder returns wrong data type when given an invalid item id

### ISSUE THREAD

**Issue by brandon15811** [UltraCart/rest_api#25]
A `CheckoutResponse` is returned instead of a `FinalizeOrderResult`

**Comment by brandon15811** [comment]
Any update on this?

**Comment by perrytew** [comment]
Brandon,
Sadly, this had gotten lost in a work queue.  I apprecate you pinging us again for a status.   We've coded up the fix, and will have it in production by noon EST today.
