### ISSUE TITLE
 Could not resolve host: https

### ISSUE THREAD

**Issue by mashhoodTechloyce** [UltraCart/rest_api#28]
i have downloaded this code and im running it on localhost, its giving me this error at 
Notice: Undefined offset: 1 in C:\xampp\htdocs\ultracart\rest_api-master\call_examples\rest_proxy.php on line 190

**Comment by perrytew** [comment]
Line 190 is part of the code that separates the header from the body of the response.
```
// now we just have the normal header and the body
$parts = explode($delimiter, $response, 2);
$header = $parts[0];
$body = $parts[1];  // << line 190
```

I haven't seen that error before with the rest_proxy.php.
To diagnose further, we need to see the response.

A few lines up, the response is logged out here:
```
if ($proxyDebug) error_log("start response ===========================================");
if ($proxyDebug) error_log("start raw response =======================================");
if ($proxyDebug) error_log($response);
if ($proxyDebug) error_log("end raw response =========================================");

```
Make sure $proxyDebug is set to true, capture the raw response, and post it here, please.

**Comment by mashhoodTechloyce** [comment]
im sorry, im a newbie, im afraid i can't find where these error_log messages are printing, in the code their is no message_type or destination parameter is set, so where these messages are going?

**Comment by mashhoodTechloyce** [comment]
found the error, i was providing https in the variable $storefronturl and it was also appending at the bottom..
