### ISSUE TITLE
Getting Error at time of  Finalize Order

### ISSUE THREAD

**Issue by gauravverma029** [UltraCart/rest_api#32]
Always Getting this error when doing finalize order.
When I am testing cart_example/template.html.

SAME CODE USING GIVEN BY YOU:- 
ERROR When doing Finalize Order --
Please provide answers to all the required item options. 

Please Guide me if anything is missing

**Comment by ucjonathan** [comment]
Do the items you are placing into the cart have item options?

**Comment by perrytew** [comment]
Gaurav,

The error means that some of the items you're adding to the cart have options and those options (such as color, size, etc) have not been properly specified for one or more items.

What merchant id and what item ids are you testing with?

Please let me know and I will advise.

**Comment by gauravverma029** [comment]
Thanks Sir, Now its resolved.
