### ISSUE TITLE
Unable to fetch order using rest v2 api getting 415 error

### ISSUE THREAD

**Issue by him-developer** [UltraCart/rest_api#37]
Hello Perry,

Hope you are well.

Recently our order fetching code started to get  **HTTP/1.1 415 Unsupported Media Type** error. 
This code which consumes rest v2 api was implemented few months back and was working good earlier.

Below is some part of response we are getting now:

```
Httpful\Response Object
(
    [body] => 
    [raw_body] => 
    [headers] => Httpful\Response\Headers Object
        (
            [headers:Httpful\Response\Headers:private] => Array
                (
                    [date] => Mon, 06 Nov 2017 19:52:48 GMT
                    [server] => Apache
                    [x-ultracart-request-id] => FF71A811A3FF82015F92E47DA2051411
                    [content-length] => 0
                )

        )

    [raw_headers] => HTTP/1.1 415 Unsupported Media Type
Date: Mon, 06 Nov 2017 19:52:48 GMT
Server: Apache
X-UltraCart-Request-Id: FF71A811A3FF82015F92E47DA2051411
Content-Length: 0
    [request] => Httpful\Request Object
        (
            [uri] => https://secure.ultracart.com/rest/v2/order/orders?email=john@example.com&_expand=item%2C+shipping&_limit=200&status=active&_sort=-order_id
            [method] => GET
            [headers] => Array
```

Thanks 
Himanshu

**Comment by ucjonathan** [comment]
Use the newer orders/query method.  Far more stable for the future as parameters are added.  Here is functional sample code.  Put your key in.  Change the email to yours.  Also, this project is for the REST API checkout.  Please post issues to the language specific SDKs on our GitHub if possible.

```
<?php

require_once __DIR__ . '/vendor/autoload.php';

// Configure API key authorization: ultraCartSimpleApiKey
ultracart\v2\Configuration::getDefaultConfiguration()->setApiKey('x-ultracart-simple-key', 'YOUR KEY GOES HERE');

// Disable SSL verification if we're having issues with this PHP install not having the proper CA installed.  Fix your CA for a production environment!
// Set debug to true if you need more information on request/response
$client = new GuzzleHttp\Client(['verify' => false, 'debug' => false]);

$api_instance = new ultracart\v2\Api\OrderApi(
    $client,
    ultracart\v2\Configuration::getDefaultConfiguration(),
    new ultracart\v2\HeaderSelector("2017-03-01")
);
$order_query = new \ultracart\v2\models\OrderQuery();
$order_query->setEmail("john@example.com");

$_limit = 200; // int | The maximum number of records to return on this one API call. (Maximum 200)
$_offset = 0; // int | Pagination of the record set.  Offset is a zero based index.
$_sort = "-order_id"; // string | The sort order of the orders.  See Sorting documentation for examples of using multiple values and sorting by ascending and descending.
$_expand = "item,shipping"; // string | The object expansion to perform on the result.

for ($_offset = 0; ; $_offset += $_limit) {
    echo 'Pulling offset ' . $_offset . PHP_EOL;
    try {
        $result = $api_instance->getOrdersByQuery($order_query, $_limit, $_offset, $_sort, $_expand);

        if ($result->getSuccess()) {
            echo 'Retrieved ' . count($result->getOrders()) . PHP_EOL;

            for ($i = 0; $i < count($result->getOrders()); $i++) {
                echo $result->getOrders()[$i]->getOrderId() . PHP_EOL;

                // Put your code here to process each of the orders that came back
//                var_dump($result->getOrders()[$i]);
            }

            // Are we done?
            if (count($result->getOrders()) < $_limit) {
                echo 'Finished' . PHP_EOL;
                break;
            } else {
//                break;
            }
        } else {
            echo 'Failed to retrieve orders' . PHP_EOL;
            var_dump($result);
            break;
        }
    } catch (Exception $e) {
        echo 'Exception when calling OrderApi->getOrdersByQuery: ', $e->getMessage(), PHP_EOL;
    }
}

?>
```

**Comment by him-developer** [comment]
Hello Jonathan,

Can you point out what we are missing in our request by checking your log or something?
I don't want to switch HTTP client for single call as we have a complete system build and rest of things are working good.

Thanks, 
him

**Comment by ucjonathan** [comment]
There are not too many fundamental differences in the API if you update.  The newer SDK uses the guzzle HTTP transport instead of cURL which may even resolve your issue.  I've given you complete sample code to test.  Give it a shot and see if that fixes your problem in a standard alone script.  If it does then there are MINOR initiation changes required to instantiate the API class.  All of that is documented in the sample above or in the sample at https://github.com/UltraCart/rest_api_v2_sdk_php

**Comment by him-developer** [comment]
Hello Jonathan,

We have implemented your solution and very thanks for that but I am little sadden by this. :( 

We are currently using Httpful which is just 16 files of 90KB and now just to fix one call I need to install whole SDK and Guzzle which around 4000 files of 23MB.

You were not willing to tell what have wrong gone with our already working request, and where rest of calls are still working good.

Thanks & Regards, 
Himanshu

**Comment by ucjonathan** [comment]
Hi Himanshu,

You have to understand things from our persoective.  We use OpenAPI to
generate the SDKs for multiple languages and can support those since we can
write sample code for it and test reproducible scenarios.

I’m glad that you were able to solve your problem.  If you want, figure out
a way to trace the way our SDK makes the call and your Httpful library and
see what the difference is.  That exercise may help you determine what you
need to change to fix it.

Best regards,
Jonathan

**Comment by ucjonathan** [comment]
Hi Himanshu,

We determine the scenario that could cause the 415 problem and added server side code to work around it.

Best regards,
Jonathan
