### ISSUE TITLE
PHP REST API Integration

### ISSUE THREAD

**Issue by mtrusty** [UltraCart/rest_api#8]
I was told by ultracart support to post this question here.

I'm trying to do an integration that keeps our customers on our site, I'm using PHP for all the API calls except for posting the credit cards so my flow looks like this

Create/Populate Cart - PHP REST call
Upload credit card to cart - JS JSONP call
Validate - PHP REST call
finalizeOrder - PHP Rest call

After the finalizeOrder I want to be able add upsell orders to the order, can finalizeAfter be used after calling finalzeOrder?  We need the credit card to be authorized for the initial sale amount right away, but we need to be able to keep the order open for subsequent upsells that may or may not be approved.

**Comment by amitavmohanty** [comment]
Hi Perry,

Need you help...

I am having the Login Failed issue when i Call FinalizeOrder from rest_proxy.php
"Login failed. Please make sure this IP has been authorized to access the system."

I am using a special user for using the api and also This is working fine when i run the pages on my local server. But when i run on the remote server it causes the issue (both the servers have ssl).

The flow is:
Create / load cart
Add item to cart
Validate
FinalizeAfter
FinalizeOrder

Any idea why this is happening ?

Regards
Amitav Mohanty

**Comment by perrytew** [comment]
Amitav,

The FinalizeOrder carries additional restrictions since it involves
merchant credentials.  You need to either 1) login to secure.ultracart.com
from the server hosting rest_proxy.php or 2) add the server IP Address to
the section that drops down from the link API Access  (see the “IP
Addresses” link next to the checkbox named “API Access”).    The reason it
works from your other server is that server was whitelisted somehow in the
past.



Thanks,

Perry

**Comment by amitavmohanty** [comment]
Thanks Parry,
But the ip of the server (50.87.229.164) along with my personal server is already placed  in the box :
https://docs.google.com/a/hitsindia.com/file/d/0B397gMRFNtxCMFZ3ZGZITVQ0UzA/edit?usp=drivesdk

Currently we are using Trial Account. Is there any restriction for this?

Regards
Amitav

**Comment by amitavmohanty** [comment]
For 1) login to secure.ultracart.com
from the server hosting rest_proxy.php 

Can you please suggest any url that i can follow. ?

Thanks & Regards
Amitav

**Comment by perrytew** [comment]
https://secure.ultracart.com/merchant/login.do

**Comment by perrytew** [comment]
No restrictions for the trial accounts.  If logging in directly from the
server doesn’t fix things, please let me know.

What merchant ID are you using?

**Comment by amitavmohanty** [comment]
Hi Perry,
We are using merchantId: SMRTX

If I open the above url, it's opening the login screen UI that I use to access Ultracart interfaces. By login to above url from proxy, do you mean I should be logging in using curl to this url?

Another question: what will happen if I call checkout after finalizeAfter before the finalization time is over? Will it create duplicate order for the same cart?

Thanks & Regards
Amitav

**Comment by amitavmohanty** [comment]
Hi Perry,
Any suggestions on the issue...

Regards
Amitav

**Comment by amitavmohanty** [comment]
Hi Perry,
Now instead of FinalizeOrder i am using checkout and after the checkout rest call i am redirecting to redirect url that ultracart handles for final processing and it opens my custom Thankyou page. So no permission issue. Seems like it works. 

Thanks 
Amitav
